version: '3.7'

services: 
  develop_1:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_develop_1
    image: pcmagas/php:dev_1
    volumes:
      - "nginx-php:/home/developer/code"

  develop_2:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_develop_2
    image: pcmagas/php:dev_2
    volumes:
      - "nginx-php:/home/developer/code"

  nginx:
    image: nginx:alpine
    ports:
      - 7880:7880
    links:
      - "develop_1:develop_1"
      - "develop_2:develop_2"
    volumes:
      - "nginx-php:/var/www/html"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
  
volumes:
  nginx-php: 
     driver: local
     driver_opts:
      o: bind
      type: none
      device: /home/pcmagas/code/docker_php_dev_stackoverflow/www
